# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG REGISTRY=quay.io
ARG OWNER=jupyter
ARG BASE_IMAGE=registry.cn-shanghai.aliyuncs.com/kcr-3rd/kesci_kernel_lab:scipy-py3.11-mpi-pybayesian-base-20240924
FROM $BASE_IMAGE

LABEL maintainer="Hu Chuan-Peng <hcp4715@hotmail.com>"

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# R pre-requisites
RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    fonts-dejavu \
    unixodbc \
    unixodbc-dev \
    r-cran-rodbc \
    gfortran \
    gcc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# macOS Rosetta virtualization creates junk directory which gets owned by root further up.
# It'll get re-created, but as USER runner after the next directive so hopefully should not cause permission issues.
#
# More info: https://github.com/jupyter/docker-stacks/issues/2296
RUN rm -rf "/home/${NB_USER}/.cache/"

# USER ${NB_UID}

# R packages including IRKernel which gets installed globally.
# r-e1071: dependency of the caret R package
RUN mamba install --yes \
    'r-base' \
    'r-caret' \
    'r-crayon' \
    'r-devtools' \
    'r-e1071' \
    'r-forecast' \
    'r-hexbin' \
    'r-htmltools' \
    'r-htmlwidgets' \
    'r-irkernel' \
    'r-nycflights13' \
    'r-randomforest' \
    'r-rcurl' \
    'r-rmarkdown' \
    'r-rodbc' \
    'r-rsqlite' \
    'r-shiny' \
    'r-tidymodels' \
    'r-tidyverse' \
    'r-brms' \
    'r-rstan' \
    'r-cmdstanr' \
    'r-ggplot2' \
    'r-dplyr' \
    'r-bayestestR' \
    'r-easystats' \
    'r-tidybayes' \
    'r-bayesplot' \
    'r-car' \
    'r-ggpubr' \
    'r-TOSTER' \
    'r-BH' \
    'r-pacman' \
    'unixodbc' && \
    mamba clean --all -f -y 

RUN R -e "install.packages(c('gridExtra', 'bruceR', 'BayesFactor', 'papaja'), \
    dependencies = TRUE, \
    repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')" && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

USER ${NB_UID}

# Expose the default Jupyter notebook port
EXPOSE 8888

# Command to start Jupyter Notebook
CMD ["start-notebook.sh"]